name: MangaLo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.4.0 # Updated version
  syncfusion_flutter_pdfviewer: ^29.1.38
  package_info_plus: ^8.3.0
  fl_chart: ^0.71.0 # Updated version
  timeago: ^3.2.2
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_analytics: ^11.4.5

  # UI and State Management
  google_fonts: ^6.2.1 # Updated version
  provider: ^6.0.5
  cached_network_image: ^3.4.1 # Updated version

  path_provider: ^2.1.5 # Updated version
  file: ^7.0.1 # Updated version
  flutter_pdfview: ^1.0.0

  # Other
  intl: ^0.20.2 # Updated version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Updated version

flutter:
  uses-material-design: true
  assets:
    - assets/covers/
    - assets/pdfs/
 
